version: '3.8'

services:
  bpp-onest-lite-up:
    build: .
    image: bpp-onest-lite-up
    container_name: bpp-onest-lite-up
    volumes:
      - ./config:/app/config
      - ./app/logs:/app/app/logs 
    environment:
      APP_ENV: ${APP_ENV}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    restart: unless-stopped
    command: ["./bpp-onest-lite", "${CONFIG_FILE}"]
